AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  iot-backend

  Testing out AppSync and cloudformation

Parameters:
  APIName:
    Type: String
    Description: "Name of the API, for generating names for the various resources"
    MinLength: 3
    MaxLength: 20
    AllowedPattern: "^[a-zA-Z][a-zA-Z0-9_]*$"

Resources:

Outputs:
